version: '3'
services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 3037:8080
    environment:
      ADMINER_DEFAULT_SERVER: "db"
      ADMINER_DESIGN: "pepa-linha"
    networks:
      - championship

  db:
    image: postgres:latest
    restart: always
    ports:
      - '${DB_PORT:-3306}:5432'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      PG_TRUST_LOCALNET: 1
    volumes:
      - 'championshipVol:/var/lib/postgresql/data'
    networks:
      - championship

networks:
  championship:
    driver: bridge

volumes:
  championshipVol:
    driver: local
